name: check_for_new_version

on:
  workflow_dispatch:  # allows for triggering workflow manually.
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  check-version:
    runs-on:
      - gha-runner-scale-set-arm64
    steps:
      - name: Update secrets
        run: |
          LATEST_VERSION=$(curl -s -I -L "https://dl.duosecurity.com/duoauthproxy-latest-src.tgz" | grep -i "content-disposition" | awk -F'filename="' '{print $2}' | awk -F'"' '{print $1}' | awk -F'-' '{print $2}')
          if [ "$LATEST_VERSION" != "${{ vars.DUO_VERSION }}" ]; then
            echo "Current version: ${{ vars.DUO_VERSION }}"
            echo "Latest version: $LATEST_VERSION"
            curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT_DEFAULT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"name\":\"DUO_VERSION\",\"value\":\"$LATEST_VERSION\"}" \
              https://api.github.com/repos/v6Org01/duoauthproxy/actions/variables/DUO_VERSION
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT_DEFAULT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "{\"event_type\":\"trigger-wf-deployProduction2K8S\"}" \
              https://api.github.com/repos/v6Org01/duoauthproxy/dispatches
          else
            echo "No new version found."
          fi
